Owl\Component\Suggestion\Model\Suggestion:
    exclusion_policy: ALL
    xml_root_name: suggestion
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [AjaxShow]
        name:
            expose: true
            type: string
            groups: [AjaxShow]
